import { Link, useParams } from "react-router";

const stories = {
  "kelp-your-neighbor": { number: "01", title: "Kelp Your Neighbor Hackathon", kicker: "Building a stronger tech culture at CSUMB", intro: "A campus-wide hackathon created to help students find collaborators, mentors, and a reason to build together.", images: ["/kelp_ur_neighbor_hackathon.png"], externalImage: undefined, paragraphs: ["I led the vision for Kelp Your Neighbor because I wanted to grow CSUMB’s tech culture. Inspired by large-scale events like CalHacks, the event was designed to make building feel welcoming, ambitious, and possible for students across campus.", "The work was deeply collaborative. I built partnerships with alumni mentors from Google and Apple, CS department leaders, the VP of Postgres, and the mayor of Monterey City. Together, we created a space where students could learn from people working across the industry.", "The result was 42+ teams, more than 80 attendees, and 10+ mentors—along with plenty of community energy, swag, and new connections."] },
  "women-in-stem": { number: "02", title: "Women in STEM podcast", kicker: "Making visibility part of the work", intro: "A conversation about finding confidence, taking initiative, and making room for more women in technology.", images: ["/podcast.png"], externalImage: undefined, paragraphs: ["I was featured on Lunch with Leaders, hosted by Adaeze Iloeje-Udeogalanya, Founder and CEO of African Women in STEM. We discussed strategies for amplifying visibility and influence in tech.", "I shared my journey from an uninvolved freshman to a student leader, and why proactive career-building matters—especially when you do not immediately see yourself represented in a field.", "The episode reached 6,000+ listeners across Apple Podcasts, Spotify, and other platforms. I’m grateful for the opportunity to turn a personal story into encouragement for someone else starting out."] },
  ottervoices: { number: "03", title: "OtterVoices: Student Spotlight", kicker: "Showing what student leadership can unlock", intro: "A CSUMB spotlight on community, connection, and the people who helped me see new possibilities.", images: [], externalImage: "https://pxl01-csumbedu.terminalfour.net/fit-in/360x640/filters:format(webp)/0x0:1080x1920/prod01/channel_2/media/csumb/social-and-video/reel-covers/computerscience-071125-005.jpg", paragraphs: ["Student leadership at CSUMB helped me build meaningful connections with campus authorities and discover opportunities I would not have known to pursue.", "Monthly meetings with Dr. Bude Su, Chair of the Computing Department, strengthened our professional relationship and gave me a chance to share my work as President of Women in Computer Science.", "That campus involvement and academic success led Dr. Su to recommend me for CSUMB’s web-update campaign. I was invited for an interview and photo/video shoot to share my Otter experience—and to show how leadership can amplify both personal and university impact."] },
  otterhacks: { number: "04", title: "OtterHacks", kicker: "Creating a first for the CSUMB community", intro: "The first CSUMB hackathon—and a crash course in delegation, event planning, and building community.", images: ["/otterhacks_leading.png", "/otterhacks_team.png"], externalImage: undefined, paragraphs: ["As President of CSUMB’s Women in Computer Science Club for one year, I focused on amplifying underrepresented voices in a male-dominated field.", "I organized CSUMB’s first hackathon, OtterHacks, and partnered with Google to bring the #IAMRemarkable workshop to campus. I also launched Unlock Open Source, an initiative featuring guest speaker Utsab Saha to help students take their first steps toward open-source contribution.", "The experience taught me how to delegate, plan events, advertise, and network—while building a supportive community that could last beyond a single event."] },
} as const;

export default function AboutStory() {
  const story = stories[useParams().story as keyof typeof stories] ?? stories["kelp-your-neighbor"];
  return <main className="story-page"><Link className="back-link" to="/about">← Back to about</Link><header className="story-hero"><p className="eyebrow">Personal development · {story.number}</p><h1>{story.title}</h1><p className="story-kicker">{story.kicker}</p><p className="story-intro">{story.intro}</p></header><div className="story-detail-grid"><div className="story-images">{story.images.map((image) => <img key={image} src={image} alt="" />)}{story.externalImage && <img src={story.externalImage} alt="CSUMB Computer Science student spotlight" />}</div><div className="story-detail-copy">{story.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<a className="story-contact" href="mailto:achsahmaria.jojo@gmail.com">Talk with me about it <span>↗</span></a></div></div></main>;
}
